<a href="https://colab.research.google.com/github/yiwenwangANU/AdvancedTool/blob/master/2_Preliminaries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Fundamentals

In [1]:
import torch

In [3]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
x.shape

torch.Size([12])

In [8]:
X = x.reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [9]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [10]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [11]:
Y = torch.ones(3,4)
Y

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
torch.concat((X, Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]])

In [14]:
torch.concat((X, Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  1.,  1.,  1.,  1.],
        [ 4.,  5.,  6.,  7.,  1.,  1.,  1.,  1.],
        [ 8.,  9., 10., 11.,  1.,  1.,  1.,  1.]])

Read from file

In [15]:
import os

In [17]:
os.makedirs("data", exist_ok=True)

In [31]:
datafile = os.path.join("data", "house_tiny.csv")
with open(datafile, "w") as f:
  f.write('''NumRooms, RoofType, Price
  NA,NA, 1275002
  2, NA, 10600
  4, slate, 178100
  NA,NA, 14000''')

In [43]:
import pandas as pd

df = pd.read_csv(datafile)
df

NumRooms  RoofType    Price
0       NA       NaN  1275002
1        2        NA    10600
2        4     slate   178100
3       NA       NaN    14000

In [67]:
inputs,targets = df.iloc[:, 0:2], df.iloc[:, -1]

In [68]:
inputs

NumRooms  RoofType
0       NA       NaN
1        2        NA
2        4     slate
3       NA       NaN

In [69]:
targets

0    1275002
1      10600
2     178100
3      14000
Name:  Price, dtype: int64

Data Preprocessing

In [70]:
roofType = inputs.columns[-1]
inputs = pd.get_dummies(inputs, columns=[roofType], dummy_na=True)
inputs

NumRooms   RoofType_ NA   RoofType_ slate   RoofType_nan
0       NA          False             False           True
1        2           True             False          False
2        4          False              True          False
3       NA          False             False           True

In [79]:
numRooms = inputs.columns[0]
inputs[numRooms] = pd.to_numeric(inputs[numRooms], errors="coerce")
inputs[numRooms] = inputs[numRooms].fillna(inputs[numRooms].mean())
inputs

NumRooms   RoofType_ NA   RoofType_ slate   RoofType_nan
0       3.0          False             False           True
1       2.0           True             False          False
2       4.0          False              True          False
3       3.0          False             False           True

Dot Product

In [90]:
x1 = torch.arange(3, dtype=torch.float32)
x2 = torch.ones(3)
torch.dot(x1, x2)

tensor(3.)

Matrix Multiplication

In [93]:
x1 = torch.arange(6, dtype=torch.float32).reshape(2,3)
x2 = torch.ones(2,3)
torch.matmul(x1.T, x2)

tensor([[3., 3., 3.],
        [5., 5., 5.],
        [7., 7., 7.]])

Norm

In [95]:
X = torch.arange(10, dtype=torch.float32)
torch.norm(X)

tensor(16.8819)

In [96]:
torch.abs(X).sum()

tensor(45.)